server:
  port: 8888


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iZoneHub?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: mccoy
    password: (C,ybJ27h%~YuEk~b!lA

  jpa:
    hibernate:
      ddl-auto: update

